config/routes.rb
Rails.application.routes.draw do
  resources :themes
  get 'pages/home'

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :rooms do
    resources :bookings, only: [:create]
  end
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :photos

  namespace :api do
    resources :rooms do
      resources :bookings, only: [:create, :update, :destroy]
    end
  end

  post '/preload' => 'bookings#preload'
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :themes
  has_many :photos, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :guests, through: :bookings, source: :user

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bedroom_count, presence: true
  validates :bathroom_count, presence: true
  validates :listing_name, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {maximum: 500}
  validates :address, presence: true

  scope :single_bedroom, -> { where(bedroom_count: 1) }
  scope :for_couples, -> { single_bedroom.where(accommodate: 2) }

  def bargain?
    price < 30
  end

  def self.order_by_price
    order(:price)
  end

  def available?(checkin, checkout)
    bookings.each do |booking|
      if (booking.starts_at <= checkout) && (booking.ends_at >= checkin)
        return false
      end
    end

    true
  end

  def current_and_future_bookings
    today = Date.today
    bookings.where("starts_at >= ? OR ends_at >= ?", today, today)
  end

end #class end

app/controllers/api/rooms_controller.rb
class Api::RoomsController < Api::BaseController
  def index
    rooms = Room.all
    render status: 200, json: rooms
  end

  def show
    room = Room.find(params[:id])
    render status: 200, json: room
  end

  def create
    room = @user.rooms.build(room_params)

    if room.save
      render status: 200, json: room
    else
      render status: 422, json: {
        errors: room.errors
      }.to_json
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy

    render status: 200, json: {
      message: "Room successfully deleted"
    }.to_json
  end

  def update
    room = Room.find(params[:id])

    if room.update(room_params)
      render status: 200, json: room
    else
      render status: 500, json: {
        message: "The room could not be updated",
        errors: room.errors
      }.to_json
    end
  end

  private

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate, :bedroom_count, :bathroom_count, :listing_name, :description, :address, :has_tv, :has_kitchen, :has_airco, :has_heating, :has_internet, :price, :active, theme_ids: [])
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def show
    @themes = @room.themes
    @photos = @room.photos
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      image_params.each do |image|
        @room.photos.create(image: image)
      end

      redirect_to edit_room_path(@room), notice: "Room successfully created"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @room.user.id
      @photos = @room.photos
    else
      redirect_to root_path, notice: "You don't have permission."
    end
  end

  def update
    if @room.update(room_params)
      image_params.each do |image|
        @room.photos.create(image: image)
      end

      redirect_to edit_room_path(@room), notice: "Room successfully updated"
    else
      render :edit
    end
  end

  private
  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:home_type, :room_type, :accommodate, :bedroom_count, :bathroom_count, :listing_name, :description, :address, :has_tv, :has_kitchen, :has_airco, :has_heating, :has_internet, :price, :active, theme_ids: [])
  end

  def image_params
    params[:images].present? ? params.require(:images) : []
  end

end #class end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for @room, html: { multipart: true } do |f| %>
    <div class="form-group">
      <label>Home Type</label>
      <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]], id: "home_type", prompt: "Select home type", class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Room Type</label>
      <%= f.select :room_type, [["Entire","Entire"], ["Private", "Private"], ["Shared", "Shared"]], prompt: "Select room type", class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Number of People</label>
      <%= f.select :accommodate, [["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6+", 6]], prompt: "Select number of people", class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Bedrooms</label>
      <%= f.select :bedroom_count, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], prompt: "Select number of bedrooms", class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Bathrooms</label>
      <%= f.select :bathroom_count, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], prompt: "Select number of bathrooms", class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Listing name</label>
      <%= f.text_field :listing_name, placeholder: "Listing name", class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Description</label>
      <%= f.text_area :description, rows: 5, placeholder: "Say something about your place", class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Address</label>
      <%= f.text_field :address, placeholder: "Address", class: "form-control" %>
    </div>

    <label>Amenities</label>

    <div class="form-group">
      <%= f.check_box :has_tv %> TV
    </div>
    <div class="form-group">
      <%= f.check_box :has_kitchen %> Kitchen
    </div>
    <div class="form-group">
      <%= f.check_box :has_internet %> Internet
    </div>

    <div class="form-group">
      <%= f.check_box :has_heating %> Heating
    </div>
    <div class="form-group">
      <%= f.check_box :has_airco %> Air Conditioning
    </div>

    <label>Themes</label>

    <%= f.collection_check_boxes(:theme_ids, Theme.all, :id, :name) do |b| %>
        <div class="form-group">
          <%= b.check_box(class: "check_box") %> <%= b.object.name %>
        </div>
    <% end %>

    <div class="form-group">
      <label>Nightly Price</label>
      <div class="input-group">
        <div class="input-group-addon">€</div>
        <%= f.number_field :price, placeholder: "eg. 100", class: "form-control" %>
      </div>
    </div>

    <label>Photos</label>

    <div class="form-group">
      <span class="btn btn-default">
        Upload Photos
        <%= file_field_tag "images[]", type: :file, multiple: true %>
      </span>
    </div>

    <div id="photos">
      <%= render 'photos/list' %>
    </div>

    <label>Publish this place?</label>

    <div class="form-group">
      <%= f.check_box :active %> Active
    </div>

    <div class="actions">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit place
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", rooms_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Listings
      </div>
      <div class="panel-body">

        <% @rooms.each do |room| %>
            <div class="row">
              <div class="col-md-7">
                <h4><%= room.listing_name %></h4>
              </div>
              <div class="col-md-3 right">
                <%= link_to "View", room, class: "btn btn-default" %>
                <%= link_to "Update", edit_room_path(room), class: "btn btn-default" %>
              </div>
            </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new place", new_room_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new place
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="panel panel-primary">

  <!-- Booking Form -->
  <% if current_user != @room.user %>
      <div class="panel panel-primary">
        <div class="panel-heading">Book this room</div>

        <div class="panel-body">
          <%= render 'bookings/form' %>
        </div>
      </div>
  <% end %>

  <div class="panel-heading"><%= @room.listing_name %></div>

  <div class="panel-body">

    <p>Address: <%= @room.address %></p>
    <p>Host: <%= @room.user.email %></p>

    <!-- Main Info -->
    <h4>Main Info</h4>
    <p>Home Type: <%= @room.home_type %></p>
    <p><%= @room.accommodate %> <%= @room.accommodate > 1 ? "Guests" : "Guest" %></p>
    <p><%= @room.bedroom_count %> <%= @room.bedroom_count > 1 ? "Bedrooms" : "Bedroom" %></p>
    <p><%= @room.bathroom_count %> <%= @room.bathroom_count > 1 ? "Bathrooms" : "Bathroom" %></p>

    <!-- About -->
    <h4>About</h4>
    <p><%= @room.description %></p>

    <!-- Amenities -->
    <h4>Amenities</h4>
    <ul class="amenities">
      <li><%= !@room.has_tv ? ("<s>TV</s>").html_safe : "TV" %></li>
      <li><%= !@room.has_kitchen ? ("<del>Kitchen</del>").html_safe : "Kitchen" %></li>
      <li><%= !@room.has_internet ? ("<del>Internet</del>").html_safe : "Internet" %></li>
      <li><%= !@room.has_heating ? ("<del>Heating</del>").html_safe : "Heating" %></li>
      <li><%= !@room.has_airco ? ("<del>Air Conditioning</del>").html_safe : "Air Conditioning" %></li>
    </ul>

    <!-- Themes -->
    <h4>Themes</h4>
    <% @themes.each do |theme| %>
        <span class="label label-success"><%= theme.name %></span>
    <% end %>

    <!-- Photos -->
    <h4>Photos</h4>
    <% @room.photos.each do |photo| %>
        <%= image_tag photo.image %>
    <% end %>

  </div>

</div>

<%= link_to "Back", rooms_path, class: "btn btn-default" %>